# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://www.heraglobaltech.com
title: Hera Global Tech
email: info@HeraGlobalTech.com
author: Brady Sheehan
description: > 
  Hera Global Tech is a biotechnology company with a focus on personal health and safety solutions
  using cutting edge sensors and machine learning technologies.
copyright: 'Copyright &copy; 2018 Hera Global Tech, inc. All Rights Reserved.'
# credits: 'info@HeraGlobalTech.com'
repository: heraglobaltech/heraglobaltech.github.io

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

social:
  - title: twitter
    url: https://twitter.com/hera_globaltech
  - title: linkedin
    url: https://www.linkedin.com/company/13463389/
  - title: instagram
    url: http://instagram.com/hera_globaltech
  - title: vimeo
    url: https://vimeo.com/heraglobaltech